[package]
name = "ariel-os-utils"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
const_panic = { workspace = true }
const-str = { workspace = true }
# env utils
konst = { workspace = true, features = ["parsing"] }
