---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: kaspar030/riot.rs-build:latest
  commands:
  - whoami
  - set
  - cargo install laze
  - cargo install just
  - laze task install-toolchain
  - laze task install-c2rust
  - laze task clone-riot
  - just test
---
kind: signature
hmac: 23912ded728fa9d2203dc9d1bfc01b867de051fa3834cee29f3106503612114b

...
