---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: kaspar030/riot.rs-build:latest
  commands:
  - whoami
  - set
  - cargo install just
  - just install-reqs
  - just clone-riot
  - just test
---
kind: signature
hmac: 84f300131480c222ed7d034bbec3836c59cd358e3b5ea597fc8b0936573a6bec

...
