---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: kaspar030/riot.rs-build:latest
  commands:
  - whoami
  - set
  - cargo install laze
  - laze task install-toolchain
  - laze task install-c2rust
  - laze task clone-riot
  - laze -C src/riot-rs-rt task -b lm3s6965evb cargo-test
  - laze -C src/riot-rs-core task -b lm3s6965evb cargo-test
---
kind: signature
hmac: 4038fde6b745c83a8d0574657d356154217b86af40e41283b403ae41ac6196e2

...
