[default.extend-words]
hax = "hax"
hsi = "hsi"
extint = "extint"     # External interrupt
synopsys = "synopsys" # Manufacturer name
COSE = "COSE"         # A technology we use

[files]
extend-exclude = [
  "book/src/*.svg",
  "src/ariel-os-rp/src/cyw43/firmware/README.md",
]
