[workspace]
members = [
    "src/*",
    "src/riot-rs-boards",
    "src/riot-rs-boards/lm3s6965evb",
    "src/riot-rs-boards/nrf52",
    "src/riot-rs-boards/nrf52840dk",
    "src/riot-rs-boards/nucleo-f401re",
    "src/riot-rs-chips",
    "src/lib/*",
    "examples/*",
    ]

exclude = [ "src/lib" ]

default-members = [
    "examples/hello-world",
    ]

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false
opt-level = 1

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = "s"

[patch.crates-io]
cortex-m = { git = "https://github.com/kaspar030/cortex-m" }
cortex-m-rt = { git = "https://github.com/kaspar030/cortex-m-rt" }
cortex-m-semihosting = { git = "https://github.com/rust-embedded/cortex-m-semihosting", rev = "8ab74cdb8c9ab669ded328072447ea6f6054ffe6" }
linkme = { git = "https://github.com/kaspar030/linkme", branch = "split_out_none_os" }
riot-sys = { git = "https://gitlab.com/kaspar030/riot-sys", branch = "support_riot-build" }
riot-wrappers = { git = "https://gitlab.com/kaspar030/riot-wrappers", branch = "add_riotrs_support" }
