[workspace]
members = [
  "src/*",
  "src/riot-rs",
  "src/riot-rs-boards",
  "src/riot-rs-boards/lm3s6965evb",
  "src/riot-rs-boards/nrf52",
  "src/riot-rs-boards/nrf52840dk",
  "src/riot-rs-boards/nucleo-f401re",
  "src/riot-rs-chips",
  "src/lib/*",
  "examples/*",
]

exclude = ["src/lib"]

default-members = ["examples/hello-world"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2021"

[workspace.dependencies]
cfg-if = { version = "1.0.0" }
cortex-m = { version = "0.7", default-features = false }
cortex-m-rt = { version = "0.7" }

nrf52832-hal = { version = "0.16.*", default-features = false }
nrf52840-hal = { version = "0.16.*" }
nrf51-hal = { version = "0.14.*" }

riot-rs = { path = "src/riot-rs" }
riot-rs-rt = { path = "src/riot-rs-rt" }

riot-wrappers = { version = "^0.8", default-features = false, features = [ "with_riot_rs" ] }

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false
opt-level = 1

[profile.release]
incremental = false
codegen-units = 1
debug = true
lto = false
opt-level = "s"

[patch.crates-io]
# "cortex-m" fork for providing ld-memory, isr stack at ram start and XFA support
cortex-m = { git = "https://github.com/kaspar030/cortex-m", branch = "riot-rs" }
cortex-m-rt = { git = "https://github.com/kaspar030/cortex-m", branch = "riot-rs" }
cortex-m-semihosting = { git = "https://github.com/kaspar030/cortex-m", branch = "riot-rs" }
# these have some patches to support riot.rs
riot-sys = { git = "https://github.com/kaspar030/rust-riot-sys", branch = "update_riot_rs_support" }
riot-wrappers = { git = "https://github.com/kaspar030/rust-riot-wrappers", branch = "add_riotrs_support" }
# these are listed so deps doesn't pull from crates.io
# (there are dummy crates so riot-wrappers / riot-sys compile while riot-rs has not published any crates)
riot-build = { path = "src/riot-build" }
riot-rs-core = { path = "src/riot-rs-core" }
# runqueue is split out. the repo also provides a version implemented in hackspec.
riot-rs-runqueue = { git = "https://github.com/future-proof-iot/riot-rs-runqueue", branch = "main" }

# these are patched to work with critical-section, and support ldmemory (boot loader offsets)
nrf52840-hal = { git = "https://github.com/kaspar030/nrf-hal", branch = "nrf52840_use_ldmemory" }
nrf52840-pac = { git = "https://github.com/kaspar030/nrf-pacs", branch = "riot-rs" }
nrf52832-pac = { git = "https://github.com/kaspar030/nrf-pacs", branch = "riot-rs" }
embassy-macros = { git = "https://github.com/kaspar030/embassy", branch = "for-riot-rs" }
embassy-executor = { git = "https://github.com/kaspar030/embassy", branch = "for-riot-rs" }
embassy-nrf = { git = "https://github.com/kaspar030/embassy", branch = "for-riot-rs" }
embassy-time = { git = "https://github.com/kaspar030/embassy", branch = "for-riot-rs" }
embassy-sync = { git = "https://github.com/kaspar030/embassy", branch = "for-riot-rs" }
