[workspace]
members = [
    "riot-app",
    "riot-build",
    "riot-rs-rt",
    "riot-rs-core",
    #"chips/cortexm",
    "boards",
    "boards/lm3s6965evb",
    "boards/nrf52",
    "boards/nrf52840dk",
    "boards/nucleo-f401re",
    "chips",
    "chips/stm32f4xx",
    "examples/*",
    ]

default-members = [
    "examples/hello-world",
    ]

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false
opt-level = 1

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = "s"

[patch.crates-io]
cortex-m = { git = "https://github.com/kaspar030/cortex-m" }
cortex-m-rt = { git = "https://github.com/kaspar030/cortex-m-rt" }
cortex-m-semihosting = { git = "https://github.com/rust-embedded/cortex-m-semihosting", rev = "8ab74cdb8c9ab669ded328072447ea6f6054ffe6" }
linkme = { git = "https://github.com/kaspar030/linkme", branch = "split_out_none_os" }
riot-sys = { path = "/home/kaspar/src/own/rust/riot-sys" }
riot-wrappers = { path = "/home/kaspar/src/own/rust/riot-wrappers" }
