[workspace]
members = [
    "riot_core",
    #"chips/cortexm",
    "app",
    "testing",
    ]

default-members = [
    "app",
    ]

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false
opt-level = 1

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = "s"
