[workspace]
members = [
  "src/*",
  "src/riot-rs",
  "src/riot-rs-boards",
  "src/riot-rs-boards/lm3s6965evb",
  "src/riot-rs-boards/nrf52",
  "src/riot-rs-boards/nrf52840dk",
  "src/riot-rs-boards/nucleo-f401re",
  "src/riot-rs-chips",
  "src/lib/*",
  "examples/*",
]

exclude = ["src/lib"]

default-members = ["examples/hello-world"]

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false
opt-level = 1

[profile.release]
incremental = false
codegen-units = 1
debug = true
lto = false
opt-level = "s"

[patch.crates-io]
# these three are forks to get a version that's current and allows "no-semihosting"
cortex-m = { git = "https://github.com/kaspar030/cortex-m" }
cortex-m-rt = { git = "https://github.com/kaspar030/cortex-m" }
cortex-m-semihosting = { git = "https://github.com/kaspar030/cortex-m" }
# these have some patches to support riot.rs
riot-sys = { git = "https://gitlab.com/kaspar030/riot-sys", branch = "add_riotrs_support" }
riot-wrappers = { git = "https://gitlab.com/kaspar030/riot-wrappers", branch = "add_riotrs_support" }
# these are listed so deps doesn't pull from crates.io
riot-build = { path = "src/riot-build" }
riot-rs-core = { path = "src/riot-rs-core" }
riot-rs-runqueue = { git = "https://github.com/future-proof-iot/riot-rs-runqueue", branch = "main" }

nrf52840-hal = { git = "https://github.com/kaspar030/nrf-hal", branch = "nrf52840_use_ldmemory" }
