[package]
name = "riot"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2018"

[dependencies]
riot-rs-rt = { path = "../riot-rs-rt" }
riot-rs-core = { path = "../riot-rs-core" }
riot-rs-boards = { path = "../riot-rs-boards" }
riot-build = { version = "0.1.0", features = ["riot-app"]}
