[package]
name = "espressif-esp32-devkitc"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[dependencies]
ariel-os-rt = { workspace = true, features = ["_esp32"] }
ariel-os-debug = { workspace = true }
