[package]
name = "riot-rs-embassy"
version = "0.1.0"
edition = "2021"

[dependencies]
# always
linkme.workspace = true
embassy-sync = { workspace = true }
riot-rs-core = { path = "../riot-rs-core" }
riot-rs-rt = { path = "../riot-rs-rt" }
critical-section.workspace = true

# time
embassy-time = { workspace = true, optional = true, features = [
  "nightly",
  "unstable-traits",
] }

[target.'cfg(context = "cortex-m")'.dependencies]
embassy-executor = { workspace = true, features = [
  "arch-cortex-m",
  "executor-interrupt",
  "nightly",
] }

[target.'cfg(context = "nrf52")'.dependencies]
embassy-nrf = { workspace = true, features = [
  "time-driver-rtc1",
  "time",
  "unstable-pac",
  "rt",
] }

[target.'cfg(context = "nrf52832")'.dependencies]
embassy-nrf = { workspace = true, features = [
  "nrf52832",
] }

[target.'cfg(context = "nrf52840")'.dependencies]
embassy-nrf = { workspace = true, features = [
  "nrf52840",
] }

[target.'cfg(context = "rp2040")'.dependencies]
embassy-rp = { workspace = true, features = [
  "nightly",
  "rt",
  "time-driver",
  "unstable-pac",
#  "unstable-traits",
] }

[features]
time = ["dep:embassy-time", "embassy-executor/integrated-timers"]
