[package]
name = "riot-rs-core"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2021"

links = "riot-rs-core"

[dependencies]
embedded-threads = { path = "/home/kaspar/src/own/rust/embedded-threads" }
critical-section = "1.0.0"
ref-cast = "1.0"

[features]
thread_info = []

[build-dependencies]
cbindgen = "0.15.*"

[dev-dependencies]
riot-rs-rt = { path = "../riot-rs-rt" }
riot-rs-boards = { path = "../riot-rs-boards" }
