[package]
name = "ariel-os-power"
version = "0.1.0"
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]

[target.'cfg(context = "cortex-m")'.dependencies]
cortex-m = { workspace = true }

[target.'cfg(context = "esp32")'.dependencies]
esp-hal = { workspace = true, features = ["esp32"] }

[target.'cfg(context = "esp32c3")'.dependencies]
esp-hal = { workspace = true, features = ["esp32c3"] }

[target.'cfg(context = "esp32c6")'.dependencies]
esp-hal = { workspace = true, features = ["esp32c6"] }

[target.'cfg(context = "esp32s3")'.dependencies]
esp-hal = { workspace = true, features = ["esp32s3"] }

[lints]
workspace = true

[features]
no-boards = []
doc = []
