[package]
name = "rp235x"
version = "0.1.0"
license.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(context = "rp235x")'.dependencies]
ariel-os-debug = { workspace = true, features = ["rtt-target"] }
ariel-os-embassy = { path = "../../ariel-os-embassy" }
ariel-os-rt = { path = "../../ariel-os-rt" }
