[package]
name = "dwm1001"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m-rt.workspace = true
cortex-m.workspace = true

riot-rs-rt = { path = "../../riot-rs-rt" }

# nrf52832 uses "xxAA-package" and "xxAB-package" to select the flash/memory
# size of a specific chip. "xxAB-package" is default, so disable defaults, select
# the other default "rt" and "xxAA-package".
nrf52832-hal = { default-features = false, features = [ "rt", "xxAA-package" ], version = "0.14.*" }
nrf52 = { path = "../nrf52" }
