[package]
name = "riot-rs-runqueue"
version = "0.1.2"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
license.workspace = true
edition = "2018"
description = "RIOT-rs runqueue implementation"

[lints]
workspace = true

[dependencies]
defmt = { workspace = true, optional = true }

# This is required so that F* can find the required F* model of the Rust core
# lib, as documented in the hax documentation:
# https://hacspec.org/book/quick_start/intro.html#setup-the-crate-you-want-to-verify
[target.'cfg(hax)'.dependencies]
hax-lib = { git = "https://github.com/hacspec/hax", rev = "5e3e6d2028db0ca8f583b427f770bbb7c26c7bed" }
