[package]
name = "riot-rs-rt"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2018"

[dependencies]
cortex-m = { version = "0.7", features = [ "inline-asm" ] }
cortex-m-rt = "0.6.99"
cortex-m-semihosting = "0.4.1"

[features]
silent-panic = []

[dev-dependencies]
riot-rs-boards = { path = "../riot-rs-boards" }
