[package]
name = "riot-rs-threads"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "generic embedded scheduler & IPC"
include = ["src/**/*", "LICENSE", "README.md"]
repository.workspace = true

[dependencies]
cfg-if.workspace = true
critical-section.workspace = true
riot-rs-runqueue.workspace = true

[target.'cfg(all(target_arch = "arm", target_feature = "thumb2"))'.dependencies]
# cortex-m specifics
cortex-m.workspace = true
cortex-m-rt.workspace = true
cortex-m-semihosting = "0.5.0"
panic-semihosting = { version = "0.6.0", features = ["exit"] }
