[package]
name = "nrf52840dk"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m-rt = "0.7"
cortex-m = "0.7"

riot-rs-rt = { path = "../../riot-rs-rt" }

nrf52840-hal = "0.14.*"
nrf52 = { path = "../nrf52" }
