[package]
name = "nrf52840dk"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m-rt.workspace = true
cortex-m.workspace = true

riot-rs-rt.workspace = true

nrf52840-hal.workspace = true
nrf52 = { path = "../nrf52" }
