[package]
name = "nrf52840dk"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
cortex-m-rt.workspace = true
cortex-m.workspace = true

riot-rs-rt.workspace = true

nrf52 = { path = "../nrf52", features = [ "nrf52840"] }
