[package]
name = "rpi-pico2"
version = "0.1.0"
license.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariel-os-debug.workspace = true
ariel-os-rt.workspace = true
rp235x = { path = "../../ariel-os-chips/rp235x" }
ariel-os-rp = { path = "../../ariel-os-rp", features = ["picotool"] }
