[package]
name = "riot-rs-coap"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
coapcore.path = "../lib/coapcore"
coap-handler = "0.2.0"
coap-handler-implementations = "0.5.0"
critical-section.workspace = true
embassy-futures = "0.1.1"
embassy-net = { workspace = true, features = ["udp"] }
embassy-sync.workspace = true
embedded-nal-async = "0.7"
embedded-nal-coap = "0.1.0-alpha.2"
lakers-crypto-rustcrypto = "0.6.0"
lakers = { version = "0.6.0", default-features = false }
riot-rs-debug.workspace = true
riot-rs-embassy = { workspace = true, features = ["net"] }
riot-rs-random = { workspace = true, features = ["csprng"] }
static_cell = "2.1.0"

# FIXME: Should go out eventually
hexlit = "0.5.5"

# For the udp_nal
embedded-io-async = "0.6.1"

[lints]
workspace = true

[features]
## Enables an arbitrary set of features in dependencies where dependencies fail
## if no features are configured at all.
doc = ["embassy-net/proto-ipv6", "embassy-net/medium-ip"]

## Enables defmt logging of coapcore
defmt = ["coapcore/defmt"]

# Only around while we carry the embedded-nal-async impl
proto-ipv4 = ["embassy-net/proto-ipv4"]
proto-ipv6 = ["embassy-net/proto-ipv6"]
