[package]
name = "riot-build"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2021"
links = "riot-build"

[dependencies]
cfg-if = "1.0.0"

riot-rs-rt = { path = "../riot-rs-rt" }
riot-rs-core = { optional = true, path = "../riot-rs-core" }
riot-rs-boards = { path = "../riot-rs-boards" }

[features]
riot-app = []
newlib = []
