[package]
name = "example-power"
license.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
ariel-os = { path = "../../src/ariel-os", features = ["time", "power"] }
ariel-os-boards = { path = "../../src/ariel-os-boards" }
