[book]
authors = ["Kaspar Schleiser", "Emmanuel Baccelli", "Christian Amsüss"]
language = "en"
multilingual = false
src = "src"
title = "RIOT-rs manual"

[output.html]
git-repository-url = "https://github.com/ariel-os/ariel-os"
edit-url-template = "https://github.com/ariel-os/ariel-os/edit/master/book/{path}"
