name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    container:
      image: ghcr.io/kaspar030/riot.rs-build:v0.0.1

    steps:
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3

    - name: Install toolchain
      uses: dtolnay/rust-toolchain@nightly
      with:
        targets: thumbv7m-none-eabi,thumbv7em-none-eabi

    - name: rust cache
      uses: Swatinem/rust-cache@v2

    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-binstall

    - name: Check out repository code
      uses: actions/checkout@v4

    - name: "installing prerequisites"
      run: |
        apt-get install -y ninja-build
        git config --global init.defaultBranch main
        git config --global user.email "ci@riot-labs.de"
        git config --global user.name "CI"
        cargo binstall -y --no-symlinks laze
        cargo binstall -y --no-symlinks c2rust
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: "riot-rs compilation test"
      run: laze build --builders nrf52840dk -g
